http:
  address: 0.0.0.0:4195
  debug_endpoints: true
input:
  type: read_until
  read_until:
    input:
      type: file
      file:
        path: /sample_data.txt
    restart_input: true
    condition:
      type: static
      static: false
buffer:
  type: memory
pipeline:
  threads: 1
  processors: []
output:
  type: file
  file:
    path: "/dev/null"
logger:
  prefix: service
  log_level: INFO
metrics:
  type: prometheus
  prefix: benthos
