http:
  address: 0.0.0.0:4196

input:
  type: kafka
  kafka:
    addresses:
      - localhost:9092
    consumer_group: sink_extractor
    topic: ${TARGET:logstash}_sink

output:
  type: stdout

logger:
  prefix: service
  log_level: INFO
