AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  BenthosConfig:
    Type: String
    Description: >
      A YAML configuration for the Benthos pipeline, can include any traditional
      sections except for input or buffer.
    Default: |
      pipeline:
        processors:
        - type: metadata
          metadata:
            operator: set
            key: AWS_LAMBDA_FUNCTION_VERSION
            value: "${AWS_LAMBDA_FUNCTION_VERSION}"

Resources:
  MyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: benthos-lambda
      Runtime: go1.x
      CodeUri: 'target/serverless/benthos-lambda.zip'
      Environment:
        Variables:
          BENTHOS_CONFIG:
            Ref: BenthosConfig