input:
  type: stdin
  stdin:
    multipart: true

pipeline:
  processors:
  - $ref: ./modules/group.yaml#/pipeline/processors/0
  - $ref: ./modules/filter.yaml#/pipeline/processors/0
  - $ref: ./modules/mutate.yaml#/pipeline/processors/0