pipeline:
  clone:
    image: plugins/git
    tags: true

  test:
    image: golang:1.12
    environment:
      - GOPATH=/drone
      - GO111MODULE=on
    commands:
      - make test

  release:
    image: golang:1.12
    secrets: [ github_token ]
    commands:
      curl -sL https://git.io/goreleaser | bash
    when:
      event: tag