kind: pipeline
name: default

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: test
  image: golang:1.12
  environment:
    GOPATH: /drone
    GO111MODULE: on
  commands:
    - make test

- name: docker-tags
  image: golang:1.12
  commands:
    - make docker-tags
  when:
    event: tag

- name: docker
  image: plugins/docker
  settings:
    repo: jeffail/benthos
    dockerfile: resources/docker/Dockerfile
    username: jeffail
    password:
      from_secret: docker_password
  when:
    event: tag

- name: docker-cgo-tags
  image: golang:1.12
  commands:
    - make docker-cgo-tags
  when:
    event: tag

- name: docker-cgo
  image: plugins/docker
  settings:
    repo: jeffail/benthos
    dockerfile: resources/docker/Dockerfile.cgo
    username: jeffail
    password:
      from_secret: docker_password
  when:
    event: tag

- name: release
  image: golang:1.12
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  commands:
    - curl -sL https://git.io/goreleaser | bash
  when:
    event: tag
