kind: pipeline
name: default

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: test
  image: golang:1.12
  environment:
    GOPATH: /drone
    GO111MODULE: on
  commands:
    - make test

- name: release
  image: golang:1.12
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  commands:
    - curl -sL https://git.io/goreleaser | bash
  when:
    event: tag
