builds:
  - main: cmd/benthos/main.go
    binary: benthos
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
    goarm:
      - 5
      - 6
      - 7
    ldflags:
      - -X github.com/Jeffail/benthos/lib/util/service.Version={{.Version}}
      - -X github.com/Jeffail/benthos/lib/util/service.DateBuilt={{.Date}}
archive:
  format: tar.gz
  files:
    - README.md
    - CHANGELOG.md
    - LICENSE
    - config/*
    - config/**/*
    - docs/*
    - docs/**/*
dist: target/dist
release:
  github:
    owner: Jeffail
    name: benthos
  disable: false
