builds:
  - id: benthos
    main: cmd/benthos/main.go
    binary: benthos
    goos: [ windows, darwin, linux, freebsd, openbsd ]
    goarch: [ amd64, arm, arm64 ]
    goarm: [ 5, 6, 7 ]
    ldflags: >
      -X github.com/Jeffail/benthos/v3/lib/service.Version={{.Version}}
      -X github.com/Jeffail/benthos/v3/lib/service.DateBuilt={{.Date}}
  - id: benthos-lambda
    main: cmd/serverless/benthos-lambda/main.go
    binary: benthos-lambda
    goos: [ linux ]
    goarch: [ amd64 ]
archives:
  - id: benthos
    builds: [ benthos ]
    format: tar.gz
    files:
      - README.md
      - CHANGELOG.md
      - LICENSE
      - config/*
      - config/**/*
  - id: benthos-lambda
    builds: [ benthos-lambda ]
    format: zip
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
dist: target/dist
release:
  github:
    owner: Jeffail
    name: benthos
  prerelease: auto
  disable: false