site_name: Benthos
site_description: A stream processor specialising in dull tasks.
site_author: Ashley Jeffs
theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - yaml
nav:
  - Home: '/'
  - Cookbooks: 'cookbooks/README.md'
  - Components:
    - 'Inputs': 'inputs/README.md'
    - 'Buffers': 'buffers/README.md'
    - 'Processors': 'processors/README.md'
    - 'Conditions': 'conditions/README.md'
    - 'Outputs': 'outputs/README.md'
    - 'Caches': 'caches/README.md'
    - 'Rate Limits': 'rate_limits/README.md'
    - 'Metrics': 'metrics/README.md'
    - 'Tracers': 'tracers/README.md'
  - Guides:
    - 'Getting Started': 'getting_started.md'
    - 'Serverless': 'serverless/README.md'
    - 'Configuration': 'configuration.md'
    - 'Config Interpolation': 'config_interpolation.md'
    - 'Processing Pipelines': 'pipeline.md'
    - 'Message Batching': 'batching.md'
    - 'Error Handling': 'error_handling.md'
    - 'Workflows': 'workflows.md'
    - 'Applied Examples': 'examples/README.md'
