site_name: Benthos
site_description: A stream processor specialising in dull tasks.
site_author: Ashley Jeffs
repo_url: https://github.com/Jeffail/benthos
google_analytics: ['UA-135959729-3', 'docs.benthos.dev']
theme:
  name: mkdocs
  custom_dir: resources/mkdocs/custom
  highlightjs: true
  hljs_languages:
    - yaml
nav:
  - Home: '/'
  - Cookbooks: 'cookbooks/README.md'
  - Components:
    - 'Inputs': 'inputs/README.md'
    - 'Buffers': 'buffers/README.md'
    - 'Processors': 'processors/README.md'
    - 'Conditions': 'conditions/README.md'
    - 'Outputs': 'outputs/README.md'
    - 'Caches': 'caches/README.md'
    - 'Rate Limits': 'rate_limits/README.md'
    - 'Metrics': 'metrics/README.md'
    - 'Tracers': 'tracers/README.md'
  - Guides:
    - 'Getting Started': 'getting_started.md'
    - 'Serverless': 'serverless/README.md'
    - 'Configuration': 'configuration.md'
    - 'Config Interpolation': 'config_interpolation.md'
    - 'Processing Pipelines': 'pipeline.md'
    - 'Message Batching': 'batching.md'
    - 'Error Handling': 'error_handling.md'
    - 'Performance Tuning': 'performance_tuning.md'
    - 'Monitoring': 'monitoring.md'
    - 'Workflows': 'workflows.md'
    - 'Applied Examples': 'examples/README.md'
