site_name: Benthos
theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - yaml
nav:
  - Home: /
  - Concepts: 'concepts.md'
  - Components:
    - 'Inputs': 'inputs'
    - 'Buffers': 'buffers'
    - 'Processors': 'processors'
    - 'Conditions': 'conditions'
    - 'Outputs': 'outputs'
    - 'Caches': 'caches'
    - 'Rate Limits': 'rate_limits'
    - 'Metrics': 'metrics'
    - 'Tracers': 'tracers'
  - Guides:
    - 'Getting Started': 'getting_started.md'
    - 'Pipeline': 'pipeline.md'
    - 'Message Batching': 'batching.md'
    - 'Error Handling': 'error_handling.md'
    - 'Workflows': 'workflows.md'
    - 'Config Cheats': 'configuration.md'
    - 'Config Interpolation': 'config_interpolation.md'
    - 'Interesting Examples': 'examples'