[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.15.0"

[[constraint]]
  branch = "master"
  name = "github.com/edsrzf/mmap-go"

[[constraint]]
  name = "github.com/go-mangos/mangos"
  version = "1.2.0"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "1.3.0"

[[constraint]]
  name = "github.com/nsqio/go-nsq"
  version = "1.0.7"

[[constraint]]
  branch = "master"
  name = "github.com/pebbe/zmq4"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.7.5"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"
