[[redirects]]
  from = "/docs/"
  to = "/docs/about/"

[[redirects]]
  from = "/docs/buffers"
  to = "/docs/components/buffers/"

[[redirects]]
  from = "/docs/caches"
  to = "/docs/components/caches/"

[[redirects]]
  from = "/docs/conditions"
  to = "/docs/components/conditions/"

[[redirects]]
  from = "/docs/inputs"
  to = "/docs/components/inputs/"

[[redirects]]
  from = "/docs/logger"
  to = "/docs/components/logger/"

[[redirects]]
  from = "/docs/metrics"
  to = "/docs/components/metrics/"

[[redirects]]
  from = "/docs/outputs"
  to = "/docs/components/outputs/"

[[redirects]]
  from = "/docs/processors"
  to = "/docs/components/processors/"

[[redirects]]
  from = "/docs/rate_limits"
  to = "/docs/components/rate_limits/"

[[redirects]]
  from = "/docs/tracers"
  to = "/docs/components/tracers/"

[[redirects]]
  from = "/docs/cookbooks/"
  to = "/cookbooks/"

[[redirects]]
  from = "/docs/getting_started"
  to = "/docs/guides/getting_started"

[[redirects]]
  from = "/docs/serverless"
  to = "/docs/guides/serverless/about"

[[redirects]]
  from = "/docs/configuration"
  to = "/docs/configuration/about"

[[redirects]]
  from = "/docs/configuration_testing"
  to = "/docs/configuration/unit_testing"

[[redirects]]
  from = "/docs/config_interpolation"
  to = "/docs/configuration/interpolation"

[[redirects]]
  from = "/docs/pipeline"
  to = "/docs/configuration/processing_pipelines"

[[redirects]]
  from = "/docs/batching"
  to = "/docs/configuration/batching"

[[redirects]]
  from = "/docs/error_handling"
  to = "/docs/configuration/error_handling"

[[redirects]]
  from = "/docs/performance_tuning"
  to = "/docs/guides/performance_tuning"

[[redirects]]
  from = "/docs/monitoring"
  to = "/docs/guides/monitoring"

[[redirects]]
  from = "/docs/sync_responses"
  to = "/docs/guides/sync_responses"

[[redirects]]
  from = "/docs/workflows"
  to = "/docs/configuration/workflows"

[[redirects]]
  from = "/docs/streams"
  to = "/docs/guides/streams_mode/about"