input:
  kafka_balanced:
    addresses:
      - localhost:9092 # TODO
    client_id: benthos_mutator_1
    consumer_group: benthos_mutator_group
    topics:
      - data_stream
    batching:
      count: 8 # Batch size: Tune this to increase output throughput
      period: 1s

pipeline:
  threads: 4 # This should exactly match the number of logical CPUs
  processors:
    - jmespath:
        query: |
          {
            content: content,
            entities: sentiment[?confidence > `0.3`].{
              name: entity,
              sentiment: level
            },
            language: max_by(language, &confidence).code
          }

output:
  kafka:
    addresses:
      - localhost:9092 # TODO
    client_id: benthos_mutator_1
    topic: mutated_data_stream
    max_in_flight: 1 # Try cranking this up to improve throughput.
