input:
  s3:
    region: eu-west-1 # TODO
    bucket: "TODO"
    delete_objects: false
    sqs_url: "TODO"
    sqs_body_path: Records.*.s3.object.key
    sqs_envelope_path: ""
    sqs_max_messages: 10
    credentials:
      id: "TODO"
      secret: "TODO"
      token: "TODO"
      role: "TODO"

pipeline:
  threads: 4 # Try to match the number of available logical CPU cores
  processors:
  - decompress:
      algorithm: gzip
  - unarchive:
      format: tar
  - split:
      size: 10 # The size of message batches to send to Kafka

output:
  kafka:
    addresses:
    - localhost:9092
    client_id: benthos_kafka_output
    topic: benthos_stream
    max_msg_bytes: 1000000
