http:
  address: 0.0.0.0:4197

input:
  type: read_until
  read_until:
    input:
      type: files
      files:
        path: ./sample_data.txt
    restart_input: true
    condition:
      type: static
      static: false
  processors:
  - type: throttle
    throttle:
      period: 3s

pipeline:
  processors:
  - type: text
    text:
      operator: replace
      arg: ITERATION
      value: ${!count:iterations}
  - type: unarchive
    unarchive:
      format: lines

output:
  type: kafka
  kafka:
    addresses:
    - localhost:9092
    topic: data_source
    target_version: 1.1.0
    max_msg_bytes: 10000000

logger:
  prefix: service
  level: INFO