http:
  address: 0.0.0.0:4197

input:
  read_until:
    input:
      files:
        path: ./sample_data.txt
    restart_input: true
    condition:
      static: false
  processors:
  - throttle:
      period: 3s

pipeline:
  processors:
  - text:
      operator: replace
      arg: ITERATION
      value: ${!count:iterations}
  - unarchive:
      format: lines

output:
  kafka:
    addresses:
    - localhost:9092
    topic: data_source
    target_version: 1.1.0
    max_msg_bytes: 10000000

logger:
  prefix: service
  level: INFO