global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'benthos-benchmark'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'benthos'
    scrape_interval: 5s
    static_configs:
      - targets: ['benthos:4195']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(benthos_pipeline_processor_1)_(([a-z0-9]|__)*)_(.*)'
        replacement: '${2}'
        target_label: id
      - source_labels: [__name__]
        regex: '(benthos_pipeline_processor_1)_(([a-z0-9]|__)*)_(.*)'
        replacement: '${1}_dag_${4}'
        target_label: __name__

