input:
  type: nats
  nats:
    subject: benthos_messages
    urls:
    - nats://localhost:4222
pipeline:
  processors:
    - type: json
      json:
        operator: delete
        path: title
output:
  type: http_client
  http_client:
    url: http://localhost:4195/webhooks/post/customer3
    verb: POST
