input:
  type: nats
  nats:
    subject: benthos_messages
    urls:
    - nats://localhost:4222
pipeline:
  processors:
    - type: filter
      filter:
        type: jmespath
        jmespath:
          query: |
            keys(@) | contains(@, 'title')
output:
  type: http_client
  http_client:
    url: http://localhost:4195/webhooks/post/customer1
    verb: POST
