input:
  type: read_until
  read_until:
    condition:
      type: static
      static: false
    input:
      type: file
      file:
        path: ./sample.json
    restart_input: true
pipeline:
  processors:
    - type: throttle
      throttle:
        period: 3s
output:
  type: nats
  nats:
    subject: benthos_messages
    urls:
      - nats://localhost:4222
