http:
  address: 0.0.0.0:4195
  debug_endpoints: true

input:
  type: broker
  broker:
    copies: 1
    inputs:
    - type: http_server
    - type: read_until
      read_until:
        input:
          type: file
          file:
            path: /sample_data.txt
        restart_input: true
        condition:
          type: static
          static: false

buffer:
  type: none

pipeline:
  threads: 1
  processors:
  - type: compress

output:
  type: broker
  broker:
    pattern: greedy
    copies: 1
    outputs:
    - type: drop

logger:
  prefix: service
  level: INFO

metrics:
  type: prometheus
  prefix: benthos

tracer:
  type: jaeger
  jaeger:
    agent_address: 'jaeger:6831'
