http:
  address: 0.0.0.0:4195
  debug_endpoints: true

input:
  generate:
    interval: "1us"
    mapping: |
      root = {
        "locations": [
          {"name": "Seattle", "state": "WA"},
          {"name": "New York", "state": "NY"},
          {"name": "Bellevue", "state": "WA"},
          {"name": "Olympia", "state": "WA"}
        ]
      }

pipeline:
  processors:
    - resource: with_bloblang
    # - resource: with_jq
    # - resource: with_jmespath
    - catch:
      - log:
          message: "Err: ${! error() }"

output:
  drop: {}

processor_resources:
  - label: with_bloblang
    bloblang: '{"Cities":this.locations.filter(this.state == "WA").map_each(this.name).sort().join(", ")}'

  - label: with_jq
    jq:
      query: '{Cities: .locations | map(select(.state == "WA").name) | sort | join(", ") }'

  - label: with_jmespath
    jmespath:
      query: "locations[?state == 'WA'].name | sort(@) | {Cities: join(', ', @)}"

metrics:
  prometheus:
    push_interval: 1s
    push_job_name: benthos_push
    push_url: "http://localhost:9091"

# tracer:
#   jaeger:
#     agent_address: 'localhost:6831'
