http:
  address: 0.0.0.0:4195
  debug_endpoints: true

input:
  generate:
    interval: "1s"
    mapping: |
      root.id = uuid_v4()
      root.bar = [] # [ "foo", "bar" ]

output:
  sql_insert:
    driver: clickhouse
    dsn: clickhouse://localhost:9000/
    table: foo
    columns: [ id, bar ]
    args_mapping: '[
        this.id,
        this.bar,
    ]'

metrics:
  prometheus:
    push_interval: 1s
    push_job_name: benthos_push
    push_url: "http://localhost:9091"

# tracer:
#   jaeger:
#     agent_address: 'localhost:6831'
