http:
  address: 0.0.0.0:4197

input:
  broker:
    copies: 1
    inputs:
    - read_until:
        input:
          file:
            path: ./sample_data.txt
            max_buffer: 10000000
        restart_input: true
        condition:
          static: false

buffer:
  memory:
    limit: 100_000_000

pipeline:
  threads: 1
  processors: []

output:
  broker:
    copies: 4
    pattern: greedy
    outputs:
      - websocket:
          url: ws://localhost:4195/post/ws

logger:
  prefix: service
  level: INFO
