version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_CREATE_TOPICS: "benthos_topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
  rabbitmq:
    image: rabbitmq
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
  benthos-bridge:
    image: jeffail/benthos
    environment:
      INPUT_TYPE: "kafka_balanced"
      INPUT_KAFKA_BALANCED_ADDRESSES: "kafka:9092"
      INPUT_KAFKA_BALANCED_TOPICS: "benthos_topic"
      OUTPUT_TYPE: "amqp"
      OUTPUT_AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
      OUTPUT_AMQP_EXCHANGE: "benthos-exchange"
      OUTPUT_AMQP_EXCHANGE_TYPE: "direct"
      OUTPUT_AMQP_KEY: "benthos-key"
