version: '2'
services:
  benthos-in:
    image: jeffail/benthos
    environment:
      INPUT_TYPE: "http_server"
      INPUT_HTTP_SERVER_ADDRESS: "0.0.0.0:8080"
      OUTPUT_TYPE: "amqp"
      OUTPUT_AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
      OUTPUT_AMQP_EXCHANGE: "benthos-exchange"
      OUTPUT_AMQP_EXCHANGE_TYPE: "direct"
      OUTPUT_AMQP_KEY: "benthos-key"
    ports:
      - "8080:8080"
  rabbitmq:
    image: rabbitmq
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
