version: '3.3'

volumes:
 prometheus_data: {}
 grafana_data: {}

services:
  benthos:
    image: jeffail/benthos
    volumes:
      - ./benthos.yaml:/benthos.yaml
      - ./sample_data.txt:/sample_data.txt
    ports:
      - 4195:4195

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 6831:6831/udp
      - 16686:16686

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 8080:80

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
