input:
  type: stdin
  stdin:
    multipart: true

pipeline:
  processors:
  - type: filter_parts
    filter_parts:
      type: jmespath
      jmespath:
        query: "contains(document.content, '2')"