pipeline:
  threads: 20
  processors:
  - resource: scrape_third_party_downloads
  - catch:
      - bloblang: root = error()
  - bloblang: result = content().string()

resources:
  processors:
    scrape_third_party_downloads:
      try:
      # Grab docker dl count
      - bloblang: root = ""
      - http:
          request:
            url: https://hub.docker.com/v2/repositories/jeffail/benthos/
            verb: GET
            retries: 0
      - bloblang: |
          type = "gauge"
          source = "docker"
          dist = "docker"
          download_count = pull_count
      - resource: set_metrics

      # Grab github latest release dl count
      - bloblang: root = ""
      - http:
          request:
            url: https://api.github.com/repos/Jeffail/benthos/releases/latest
            verb: GET
            retries: 0
      - bloblang: |
          root = assets.map_each(match {
            "type":"gauge",
            "source":"github",
            "dist": name.re_replace("^benthos-?((lambda_)|_)[0-9\\.]+_([^\\.]+).*", "$2$3"),
            "download_count": download_count
          } {
            dist != "checksums" => this
            _ => deleted()
          })
      - unarchive:
          format: json_array
      - resource: set_metrics

    set_metrics:
      try:
        - switch:
           - condition:
               bloblang: type == "gauge"
             processors:
               - resource: metric.gauge
           - processors:
               - resource: metric.counter

    metric.gauge:
      metric:
        labels:
          dist: ${!json("dist")}
          source: ${!json("source")}
        path: BenthosDownloadGauge
        type: gauge
        value: ${!json("download_count")}

    metric.counter:
      metric:
        labels:
          version: ${!json("version")}
          dist: ${!json("dist")}
          source: ${!json("source")}
        path: BenthosDownload
        type: counter

metrics:
  rename:
    by_regexp:
    - pattern: '^resource\.processor\.metric\.(gauge|counter)\.(.*)$'
      value: "$2"
    child:
      whitelist:
        paths:
          - BenthosDownloadGauge
          - BenthosDownload
        child:
          prometheus:
            prefix: benthos