pipeline:
  processors:
    - cache:
        cache: foocache
        operator: set
        key: foo
        value: "static value"
    - cache:
        cache: foocache
        operator: get
        key: foo

tests:
  - name: Example test case 1
    environment: {}
    target_processors: /pipeline/processors
    input_batch:
      - content: 'ignored value'
    output_batches:
      - - content_equals: 'static value'