version: '3.3'
services:
  bento:
    image: ghcr.io/warpstreamlabs/bento
    command: [ '-c', '/bento.yaml', 'streams', '/streams/*.yaml' ]
    volumes:
      - ./bento.yaml:/bento.yaml
      - ./streams:/streams
